services:
  neo4j:
    image: neo4j:latest
    privileged: true
    volumes:
        - ./logs:/logs
        - ./config/:/config
        - ./data/:/data
        - ./plugins/:/plugins
    environment:
        - NEO4J_AUTH=none
    ports:
      - "7474:7474"
      - "7687:7687"
    hostname: wumpdata
    restart: always
    networks:
      - wumpnet
  wumpapi:
    image: wumpapi:latest
    restart: always
    ports:
      - "42069:8080"
    networks:
      - wumpnet
  wumpfront:
    image: maximummaxx/wumpfront:latest
    restart: always
    ports:
      - "8080:8080"
    networks:
      - wumpnet
networks:
  wumpnet:
    
