@wumpapi_HostAddress = http://localhost:5034
@wumpapi_AlmostProdAddress = http://localhost:42069

###
GET {{wumpapi_HostAddress}}/graph/
Accept: application/json

###
GET {{wumpapi_HostAddress}}/users
Accept: application/json
###
POST {{wumpapi_HostAddress}}/createaccount/
Content-Type: application/json

{
  "Username": "DuckMan",
  "Password": "Atticus",
  "FirstName": "Jayden",
  "LastName": "Snyder",
  "Email": "maxloseland@jayden.phindog.com"
}
###
POST {{wumpapi_HostAddress}}/login
Content-Type: application/json

{
  "Username": "DuckMan",
  "Password": "Atticus"
}
###
POST {{wumpapi_HostAddress}}/logout
Content-Type: application/json

{
  "SessionToken":"fffb07bf-d55d-47df-9661-8d1492eaa316"
}
### 
POST {{wumpapi_HostAddress}}/createRelationship
Content-Type: application/json

{
  "SessionToken": "549d31c7-7e81-488d-9b23-5a872bb0d984",
  "TargetUser": "DuckMan",
  "RelationshipName" : "Meets",
  "Data" : "HAHAHAHAhAHA"
}
###
GET {{wumpapi_HostAddress}}/graph
Accept: application/json
###
GET {{wumpapi_AlmostProdAddress}}/graph
Accept: application/json