@wumpapi_HostAddress = http://localhost:5034

GET {{wumpapi_HostAddress}}/login/
Accept: application/json

###
GET {{wumpapi_HostAddress}}/logout/
Accept: application/json
###
GET {{wumpapi_HostAddress}}/graph/
Accept: application/json

###
GET {{wumpapi_HostAddress}}/addMax/
Accept: application/json

###
GET {{wumpapi_HostAddress}}/maxWantsADummyBecauseHeIsADummy/
Accept: application/json

###
POST {{wumpapi_HostAddress}}/createaccount/
Content-Type: application/json

{
  "Username": "MinimumMaxx",
  "Password": "Something stupid from one password :/!",
  "FirstName": "Max",
  "LastName": "Loseland",
  "Email": "MinimumMaxx@gmail.com"
}
